---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-exporter
  namespace: database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-exporter
  namespace: database
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-exporter
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-exporter
subjects:
- kind: ServiceAccount
  name: postgres-exporter
  namespace: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      serviceAccountName: postgres-exporter
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        env:
        - name: DATA_SOURCE_URI
          value: "ha-db.database.svc.cluster.local:5432/appdb?sslmode=require"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: appuser.ha-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: appuser.ha-db.credentials.postgresql.acid.zalan.do
              key: password
        ports:
        - containerPort: 9187
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: database
  labels:
    app: postgres-exporter
spec:
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
      - database
  endpoints:
    - port: metrics
      interval: 30s
